schema_version: 1

context:
  name: libmicrohttpd
  version: "1.0.4"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://ftp.gnu.org/gnu/libmicrohttpd/libmicrohttpd-${{ version }}.tar.gz
  sha256: d72e5cfccd62bf2f79252edbc3828eeedc088ce71fc47b7c9e3bd7246b3d54de

build:
  number: 0
  skip: win

requirements:
  build:
    - if: unix
      then: gnuconfig
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - make
  host:
    - gnutls
  run_exports:
    - ${{ pin_subpackage("libmicrohttpd", upper_bound="x.x") }}

tests:
  - script:
      - if: unix
        then:
          - test -f $PREFIX/lib/libmicrohttpd${SHLIB_EXT}
          - test -f $PREFIX/include/microhttpd.h
about:
  license: LGPL-2.0-or-later
  license_file: COPYING
  summary: Light HTTP/1.1 server library
  homepage: https://www.gnu.org/software/libmicrohttpd/

extra:
  recipe-maintainers:
    - xhochy
